---
- name: Configuration MariaDB
  copy:
    src: files/server.cnf
    dest: /etc//etc/my.cnf.d/server.cnf
    owner: root
    group: root

- name: Restart MariaDB service.
  shell: /usr/bin/systemctl restart "{{ mariadb_service_name }}"
