---
- name: Apply nginx configuration.
  copy:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root

- name: Apply PHP configuration.
  copy:
    src: templates/www.conf.j2
    dest: /etc/php-fpm.d/www.conf
    owner: root
    group: root

- name: Create User for FTP.
  user:
    name: typo3
    shell: /bin/bash
    groups: nginx
    append: yes

- name: Create DocumentRoot.
  file:
    path: "{{ web_server_document_root }}"
    state: directory
    mode: 0755
    owner: nginx
    group: nginx
