---
- name: Start php-fpm service.
  shell: /usr/bin/systemctl start "{{ web_server_php_service }}"

- name: Start php-fpm service.
  shell: /usr/bin/systemctl enable "{{ web_server_php_service }}"

- name: Start nginx service.
  shell: /usr/bin/systemctl start "{{ web_server_nginx_service }}"

- name: Start nginx service.
  shell: /usr/bin/systemctl enable "{{ web_server_nginx_service }}"
