galaxy_info:
  author: Chatree Kunjai
  description: Ansible role for install web server on CentOS 7 hosts.
  license: MIT
  min_ansible_version: 2.2
  platforms:
  - name: CentOS
    versions:
    - 7
dependencies: []
