galaxy_info:
  author: Chatree Kunjai
  description: Ansible role for install JDK 8 on CentOS 7.
  license: MIT
  min_ansible_version: 2.2
  platforms:
  - name: CentOS
    versions:
    - 7
  galaxy_tags:
    - docker
dependencies: []
