---
  - name: Disable SELinux on CentOS
    selinux:
      state: disabled
    register: host_preparation_disable_selinux

  - name: Check if server need to reboot
    set_fact:
      host_preparation_need_reboot: true
    when: |
      host_preparation_disable_selinux.changed
