---
- name: Set TimeZone in /etc/localtime
  command: /usr/bin/timedatectl set-timezone "{{ host_preparation_timezone }}"

- name: Install ntp packages
  yum:
     name: "{{ item }}"
     state: latest
  with_items:
    - ntp

- name: Configure NTP
  template:
    src: templates/ntp.j2
    dest: /etc/ntp.conf
    owner: root
    group: wheel
    mode: 0644

- name: Set ntp-client auto start.
  command: /usr/bin/systemctl enable ntpd.service

  tags:
    - host-preparation-configure-ntp
